# Generated by Django 5.2.8 on 2025-11-08 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CovidSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(default='disease.sh', max_length=100)),
                ('cases', models.IntegerField(null=True)),
                ('today_cases', models.IntegerField(null=True)),
                ('deaths', models.IntegerField(null=True)),
                ('today_deaths', models.IntegerField(null=True)),
                ('recovered', models.IntegerField(null=True)),
                ('active', models.IntegerField(null=True)),
                ('raw', models.JSONField(blank=True, null=True)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='WorkForceTrained.district')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('facility_type', models.CharField(choices=[('clinic', 'Clinic'), ('health_center', 'Health Centre'), ('district_hospital', 'District Hospital'), ('central_hospital', 'Central Hospital'), ('private', 'Private Facility')], max_length=30)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facilities', to='WorkForceTrained.district')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='WorkForceTrained.organization')),
            ],
            options={
                'ordering': ['district__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='HealthcareWorker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('phone', models.CharField(db_index=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=20, null=True)),
                ('disability', models.BooleanField(default=False)),
                ('language', models.CharField(default='Chichewa/English', max_length=50)),
                ('position', models.CharField(blank=True, max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='healthcare_workers', to='WorkForceTrained.facility')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='healthcare_workers', to='WorkForceTrained.organization')),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Deployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outbreak_type', models.CharField(choices=[('COVID-19', 'COVID-19'), ('Cholera', 'Cholera'), ('Polio', 'Polio'), ('Ebola', 'Ebola'), ('Other', 'Other')], max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('role', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(default='ongoing', max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='WorkForceTrained.district')),
                ('hcw', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deployments', to='WorkForceTrained.healthcareworker')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='AvailabilityRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('available', 'Available'), ('unavailable', 'Unavailable'), ('deployed', 'Deployed'), ('on_leave', 'On Leave')], max_length=20)),
                ('note', models.TextField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('hcw', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_records', to='WorkForceTrained.healthcareworker')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(blank=True, max_length=200)),
                ('date_completed', models.DateField()),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to='certificates/')),
                ('competency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='WorkForceTrained.competency')),
                ('hcw', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainings', to='WorkForceTrained.healthcareworker')),
            ],
            options={
                'ordering': ['-date_completed'],
            },
        ),
        migrations.AddIndex(
            model_name='healthcareworker',
            index=models.Index(fields=['phone'], name='WorkForceTr_phone_877e73_idx'),
        ),
        migrations.AddIndex(
            model_name='healthcareworker',
            index=models.Index(fields=['last_name', 'first_name'], name='WorkForceTr_last_na_440b41_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='facility',
            unique_together={('name', 'district')},
        ),
        migrations.AlterUniqueTogether(
            name='training',
            unique_together={('hcw', 'competency', 'date_completed')},
        ),
    ]
