# Generated by Django 5.2.8 on 2025-11-26 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkForceTrained', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deployment',
            name='outbreak_type',
            field=models.CharField(choices=[('COVID-19', 'COVID-19'), ('Cholera', 'Cholera'), ('Polio', 'Polio'), ('Ebola', 'Ebola'), ('Malaria', 'Malaria'), ('Measles', 'Measles'), ('Other', 'Other')], max_length=50),
        ),
        migrations.DeleteModel(
            name='CovidSnapshot',
        ),
    ]
