# Generated by Django 5.2.8 on 2025-11-26 12:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkForceTrained', '0002_alter_deployment_outbreak_type_delete_covidsnapshot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeploymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hcw_name', models.CharField(max_length=255)),
                ('hcw_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('hcw_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('hcw_position', models.CharField(blank=True, max_length=120, null=True)),
                ('district_name', models.CharField(max_length=100)),
                ('outbreak_type', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('role', models.CharField(blank=True, max_length=120)),
                ('deployment_name', models.CharField(blank=True, max_length=200, null=True)),
                ('urgency', models.CharField(default='medium', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('original_deployment_id', models.IntegerField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
                ('completion_notes', models.TextField(blank=True, null=True)),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Deployment Histories',
                'ordering': ['-archived_at'],
            },
        ),
    ]
