# Generated by Django 5.2.8 on 2025-11-26 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkForceTrained', '0003_deploymenthistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deployment',
            name='status',
            field=models.CharField(default='status', max_length=50),
        ),
    ]
